---
# tasks file for kibana
- name: copy rpm to tmp
  copy:
    src: files/kibana-7.17.8-x86_64.rpm
    dest: /tmp/kibana-7.17.8-x86_64.rpm

- name: Install Kibana.
  dnf:
    name: "{{ kibana_package }}"
    state: "{{ kibana_package_state }}"
    disable_gpg_check: true

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: "{{ kibana_service_state }}"
    enabled: "{{ kibana_service_enabled }}"

- name: Copy Kibana configuration.
  template:
    src: "{{ kibana_config_template }}"
    dest: "{{ kibana_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana